/*
 * This source file was generated by the Gradle 'init' task
 */
package app.src.main.java;

import trafficControlSystem.basic.Main;

public class App {
    public String getGreeting() {
        Main tcs = new Main();
        tcs.run();
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
